brew "stow"
brew "starship"
brew "fish"
brew "jq"
brew "neovim"
brew "koekeishiya/formulae/yabai"
# cask "karabiner-elements"
# cask "microsoft-edge"
# cask "iterm2"
# cask "slack"
# cask "spotify"
# cask "raycast"
# cask "visual-studio-code"
