add_newline=false

[line_break]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[git_status]
disabled = true

[nodejs]
disabled = true

# [python]
# disabled = true

[package]
disabled = true

[container]
disabled = true

[cmd_duration]
disabled = true
